/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/JswwOSqCjsP
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Libre_Franklin } from 'next/font/google'

libre_franklin({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link"
import Image from "next/image"

export default function Page() {
  return (
    <div className="flex flex-col min-h-[100dvh]">
      <header className="px-4 lg:px-6 h-14 flex items-center">
        <Link className="flex items-center justify-center" href="#">
          <MountainIcon className="h-6 w-6" />
          <span className="sr-only">Portfolio</span>
        </Link>
      </header>
      <main className="flex-1 place-items-center">
        <section className="w-full pt-12 md:pt-24 lg:pt-32">
          <div className="container mx-auto space-y-10 xl:space-y-16">
            <div className="grid gap-4 px-10 md:grid-cols-2 md:gap-16">
              <div>
                <h1 className="lg:leading-tighter text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl xl:text-[3.4rem] 2xl:text-[3.75rem]">
                  Yoko Daikoku
                </h1>
                <p className="text-gray-500 mt-4 md:text-xl dark:text-gray-400">UI/UX Designer | Career Changer</p>
                <p className="text-gray-500 mt-4 md:text-xl dark:text-gray-400">
                  I'm a former accountant who found my passion in design. I'm excited to bring my unique perspective to
                  the industry.
                </p>
              </div>
              <div className="flex flex-col items-start space-y-4">
                <Image
                  alt="Yoko Daikoku"
                  className="rounded-full w-[200px] h-[200px] object-cover place-self-center"
                  height="400"
                  src="/placeholder.svg"
                  style={{
                    aspectRatio: "400/400",
                    objectFit: "cover",
                  }}
                  width="400"
                />
              </div>
            </div>
          </div>
        </section>
        <section className="w-full py-12 md:py-24 lg:py-32">
          <div className="container mx-auto px-4 md:px-6">
            <div className="flex flex-col items-center justify-center space-y-4 text-center">
              <div className="space-y-2 my-8">
                <h2 className="text-3xl font-bold tracking-tighter sm:text-5xl">Work Experience</h2>
              </div>
            </div>
            <div className="mx-auto grid items-start gap-8 sm:max-w-4xl sm:grid-cols-2 md:gap-12 lg:max-w-5xl lg:grid-cols-3">
              <div className="grid gap-1">
                <h3 className="text-lg font-bold">Accountant</h3>
                <p className="text-sm text-gray-500 dark:text-gray-400">ABC Accounting Firm | 2018 - 2022</p>
                <p className="text-sm text-gray-500 dark:text-gray-400">
                  Responsible for preparing financial statements, managing accounts payable and receivable, and
                  providing financial analysis to clients.
                </p>
              </div>
              <div className="grid gap-1">
                <h3 className="text-lg font-bold">Freelance Designer</h3>
                <p className="text-sm text-gray-500 dark:text-gray-400">2022 - Present</p>
                <p className="text-sm text-gray-500 dark:text-gray-400">
                  Worked with various clients to create user-friendly and visually appealing designs for websites,
                  mobile apps, and marketing materials.
                </p>
              </div>
              <div className="grid gap-1">
                <h3 className="text-lg font-bold">Design Intern</h3>
                <p className="text-sm text-gray-500 dark:text-gray-400">XYZ Design Agency | Summer 2021</p>
                <p className="text-sm text-gray-500 dark:text-gray-400">
                  Assisted the design team in creating wireframes, prototypes, and final designs for various client
                  projects.
                </p>
              </div>
            </div>
          </div>
        </section>
        <section className="w-full py-12 md:py-24 lg:py-32">
          <div className="container mx-auto px-4 md:px-6">
            <div className="flex flex-col items-center justify-center space-y-4 text-center">
              <div className="space-y-2 my-8">
                <h2 className="text-3xl font-bold tracking-tighter sm:text-5xl">Education</h2>
              </div>
            </div>
            <div className="mx-auto grid items-start gap-8 sm:max-w-4xl sm:grid-cols-2 md:gap-12 lg:max-w-5xl lg:grid-cols-3">
              <div className="grid gap-1">
                <h3 className="text-lg font-bold">Bachelor of Accounting</h3>
                <p className="text-sm text-gray-500 dark:text-gray-400">University of XYZ | 2014 - 2018</p>
                <p className="text-sm text-gray-500 dark:text-gray-400">
                  Graduated with a 3.8 GPA and received the Dean's List award.
                </p>
              </div>
              <div className="grid gap-1">
                <h3 className="text-lg font-bold">Certificate in UI/UX Design</h3>
                <p className="text-sm text-gray-500 dark:text-gray-400">Coursera | 2021 - 2022</p>
                <p className="text-sm text-gray-500 dark:text-gray-400">
                  Completed a comprehensive program in user experience design, including courses in design thinking,
                  prototyping, and user research.
                </p>
              </div>
            </div>
          </div>
        </section>
        <section className="w-full py-12 md:py-24 lg:py-32">
          <div className="container mx-auto px-4 md:px-6">
            <div className="flex flex-col items-center justify-center space-y-4 text-center">
              <div className="space-y-2 my-8">
                <h2 className="text-3xl font-bold tracking-tighter sm:text-5xl">Skills</h2>
              </div>
            </div>
            <div className="mx-auto grid items-start gap-8 sm:max-w-4xl sm:grid-cols-2 md:gap-12 lg:max-w-5xl lg:grid-cols-3">
              <div className="grid gap-1">
                <h3 className="text-lg font-bold">Design Tools</h3>
                <p className="text-sm text-gray-500 dark:text-gray-400">Figma, Adobe XD, Sketch</p>
              </div>
              <div className="grid gap-1">
                <h3 className="text-lg font-bold">Design Principles</h3>
                <p className="text-sm text-gray-500 dark:text-gray-400">
                  User-centered design, visual hierarchy, typography, color theory
                </p>
              </div>
              <div className="grid gap-1">
                <h3 className="text-lg font-bold">Soft Skills</h3>
                <p className="text-sm text-gray-500 dark:text-gray-400">
                  Problem-solving, communication, adaptability, creativity
                </p>
              </div>
            </div>
          </div>
        </section>
        <section className="w-full py-12 md:py-24 lg:py-32">
          <div className="container mx-auto px-4 md:px-6">
            <div className="flex flex-col items-center justify-center space-y-4 text-center">
              <div className="space-y-2 my-8">
                <h2 className="text-3xl font-bold tracking-tighter sm:text-5xl">Portfolio</h2>
              </div>
            </div>
            <div className="mx-auto grid items-start gap-8 sm:max-w-4xl sm:grid-cols-2 md:gap-12 lg:max-w-5xl lg:grid-cols-3">
              <div className="grid gap-1">
                <Image
                  alt="Project 1"
                  className="rounded-lg object-cover"
                  height="300"
                  src="/placeholder.svg"
                  style={{
                    aspectRatio: "400/300",
                    objectFit: "cover",
                  }}
                  width="400"
                />
                <h3 className="text-lg font-bold">Project 1</h3>
                <p className="text-sm text-gray-500 dark:text-gray-400">
                  Designed a responsive website for a local cafe, focusing on a clean and modern aesthetic.
                </p>
              </div>
              <div className="grid gap-1">
                <Image
                  alt="Project 2"
                  className="rounded-lg object-cover"
                  height="300"
                  src="/placeholder.svg"
                  style={{
                    aspectRatio: "400/300",
                    objectFit: "cover",
                  }}
                  width="400"
                />
                <h3 className="text-lg font-bold">Project 2</h3>
                <p className="text-sm text-gray-500 dark:text-gray-400">
                  Created a mobile app prototype for a fitness tracking service, focusing on intuitive user experience.
                </p>
              </div>
              <div className="grid gap-1">
                <Image
                  alt="Project 3"
                  className="rounded-lg object-cover"
                  height="300"
                  src="/placeholder.svg"
                  style={{
                    aspectRatio: "400/300",
                    objectFit: "cover",
                  }}
                  width="400"
                />
                <h3 className="text-lg font-bold">Project 3</h3>
                <p className="text-sm text-gray-500 dark:text-gray-400">
                  Designed marketing materials for a local non-profit organization, including a brochure and social
                  media graphics.
                </p>
              </div>
            </div>
          </div>
        </section>
      </main>
      <footer className="flex flex-col gap-2 sm:flex-row py-6 w-full shrink-0 items-center px-4 md:px-6 border-t">
        <p className="text-xs text-gray-500 dark:text-gray-400">© 2024 Jane Doe. All rights reserved.</p>
        <nav className="sm:ml-auto flex gap-4 sm:gap-6">
          <Link className="text-xs hover:underline underline-offset-4" href="#">
            LinkedIn
          </Link>
          <Link className="text-xs hover:underline underline-offset-4" href="#">
            Twitter
          </Link>
          <Link className="text-xs hover:underline underline-offset-4" href="#">
            Instagram
          </Link>
        </nav>
      </footer>
    </div>
  )
}

function MountainIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m8 3 4 8 5-5 5 15H2L8 3z" />
    </svg>
  )
}
